### ISSUE TITLE
Older media messages (Images) are flickering on conversation screen.

### ISSUE THREAD

**Issue by sojitrajayumedex** [twilio/twilio-conversations-demo-swift#5]
When we send any image if there are any older messages with the image then all images are flickering. 

Following is the preview when we send any image as a message.

https://user-images.githubusercontent.com/59594727/141974738-edf95070-f083-478d-a6ed-54e1cd960761.mov

**Comment by berkus** [comment]
Ok, thanks for the report. I'm currently changing this code, so it should be better in the next version.

**Comment by sojitrajayumedex** [comment]
@berkus Is there any update on this issue?

**Comment by networkinterfacecontroller** [comment]
Hi! We'll be releasing a retooled version of this project very shortly - stay tuned for a large update
